# Más Numpy y Scipy

## Importación de bibliotecas

In [28]:
import numpy as np
from scipy import linalg

## Funciones de agregación

### Sumatoria

In [29]:
a = np.linspace(1, 100, 100).reshape((25, 4))
a

array([[  1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.],
       [  9.,  10.,  11.,  12.],
       [ 13.,  14.,  15.,  16.],
       [ 17.,  18.,  19.,  20.],
       [ 21.,  22.,  23.,  24.],
       [ 25.,  26.,  27.,  28.],
       [ 29.,  30.,  31.,  32.],
       [ 33.,  34.,  35.,  36.],
       [ 37.,  38.,  39.,  40.],
       [ 41.,  42.,  43.,  44.],
       [ 45.,  46.,  47.,  48.],
       [ 49.,  50.,  51.,  52.],
       [ 53.,  54.,  55.,  56.],
       [ 57.,  58.,  59.,  60.],
       [ 61.,  62.,  63.,  64.],
       [ 65.,  66.,  67.,  68.],
       [ 69.,  70.,  71.,  72.],
       [ 73.,  74.,  75.,  76.],
       [ 77.,  78.,  79.,  80.],
       [ 81.,  82.,  83.,  84.],
       [ 85.,  86.,  87.,  88.],
       [ 89.,  90.,  91.,  92.],
       [ 93.,  94.,  95.,  96.],
       [ 97.,  98.,  99., 100.]])

In [30]:
a.sum()

np.float64(5050.0)

In [31]:
a.sum(axis = 0)

array([1225., 1250., 1275., 1300.])

In [32]:
a.sum(axis = 1)

array([ 10.,  26.,  42.,  58.,  74.,  90., 106., 122., 138., 154., 170.,
       186., 202., 218., 234., 250., 266., 282., 298., 314., 330., 346.,
       362., 378., 394.])

### Promedio

In [33]:
a.mean()

np.float64(50.5)

In [34]:
a.mean(axis = 0)

array([49., 50., 51., 52.])

In [35]:
a.mean(axis = 1)

array([ 2.5,  6.5, 10.5, 14.5, 18.5, 22.5, 26.5, 30.5, 34.5, 38.5, 42.5,
       46.5, 50.5, 54.5, 58.5, 62.5, 66.5, 70.5, 74.5, 78.5, 82.5, 86.5,
       90.5, 94.5, 98.5])

### Desviación estándar

In [36]:
a.std()

np.float64(28.86607004772212)

In [37]:
a.std(axis = 0)

array([28.8444102, 28.8444102, 28.8444102, 28.8444102])

In [38]:
a.std(axis = 1)

array([1.11803399, 1.11803399, 1.11803399, 1.11803399, 1.11803399,
       1.11803399, 1.11803399, 1.11803399, 1.11803399, 1.11803399,
       1.11803399, 1.11803399, 1.11803399, 1.11803399, 1.11803399,
       1.11803399, 1.11803399, 1.11803399, 1.11803399, 1.11803399,
       1.11803399, 1.11803399, 1.11803399, 1.11803399, 1.11803399])

### Varianza

In [39]:
a.var()

np.float64(833.25)

In [40]:
a.var(axis = 0)

array([832., 832., 832., 832.])

In [41]:
a.var(axis = 1)

array([1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25,
       1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25,
       1.25, 1.25, 1.25])

### Valor máximo

In [42]:
b = np.random.normal(0, 1, 100).reshape((25, 4))
b

array([[-1.62157812,  0.2925888 ,  0.19204723,  0.46820012],
       [ 0.30754269,  0.70364498,  0.84636249, -1.32654046],
       [ 0.3938091 ,  0.87180819, -0.78203456,  0.01727456],
       [-0.9982808 , -0.06816677,  0.99546397,  0.54614639],
       [-0.95065913,  0.73129506,  0.7983952 ,  0.55013766],
       [ 1.02665423, -0.46663027, -1.04465673,  0.30953207],
       [-1.47034009,  0.49727787, -0.50062713,  1.22323628],
       [ 0.41968432, -0.1889041 ,  0.24410634, -0.62703528],
       [ 0.8916259 ,  2.0430906 , -0.77434706, -0.93382421],
       [-1.10002301, -2.65369882, -0.91606596,  0.96399722],
       [ 0.40932049, -0.33708218, -1.69027681,  1.28747708],
       [ 1.0905508 , -0.67702491, -1.21841119,  0.26176588],
       [-0.56462268, -0.96039062,  0.13296293, -0.83596963],
       [-0.10669475, -1.14580192,  1.26744295,  1.69939928],
       [-1.20662306, -0.70607953, -0.62898989,  0.49677488],
       [-0.83825193,  0.95704862,  0.48917025, -0.70655384],
       [ 0.26421699,  0.

In [43]:
b.max()

np.float64(2.0430905968514677)

In [44]:
b.max(axis = 0)

array([1.0905508 , 2.0430906 , 1.26744295, 1.76962463])

In [45]:
b.max(axis = 1)

array([0.46820012, 0.84636249, 0.87180819, 0.99546397, 0.7983952 ,
       1.02665423, 1.22323628, 0.41968432, 2.0430906 , 0.96399722,
       1.28747708, 1.0905508 , 0.13296293, 1.69939928, 0.49677488,
       0.95704862, 1.72599561, 0.88163442, 1.76962463, 0.54785183,
       0.9413935 , 0.34590682, 0.52096463, 1.67032878, 0.1492681 ])