# Introducción a Numpy

## Importación de bibliotecas

In [181]:
import numpy as np

## Creación de arreglos

### Manual


Creando primero una lista simple

In [182]:
a = np.array(list(range(10)))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Una lista de listas

In [183]:
a = np.array([[1, 2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

### Constructores

Arreglo de solo 1s. Recibe una tupla para definir su forma

In [184]:
b = np.ones((4, 8))
b

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

Arreglo de solo 0s. Recibe una tupla para definir su forma

In [185]:
b = np.zeros((6, 8))
b

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

Arreglo de datos vacíos. Importante por cuestiones de optimización. Recibe una tupla para definir su forma

In [186]:
b = np.empty((5, 3))
b

array([[5.79939265e-316, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 6.32404027e-322]])

Arreglo creado por la función `.arange`. Similar a `range`, pero si acepta tamaños de paso decimal (de punto flotante)

In [187]:
c = np.arange(0, 101, 2.5)
c

array([  0. ,   2.5,   5. ,   7.5,  10. ,  12.5,  15. ,  17.5,  20. ,
        22.5,  25. ,  27.5,  30. ,  32.5,  35. ,  37.5,  40. ,  42.5,
        45. ,  47.5,  50. ,  52.5,  55. ,  57.5,  60. ,  62.5,  65. ,
        67.5,  70. ,  72.5,  75. ,  77.5,  80. ,  82.5,  85. ,  87.5,
        90. ,  92.5,  95. ,  97.5, 100. ])

Arreglo creado por la función `.linspace`. En lugar de recibir el tamaño de paso, recibe cuantos valores quieres entre el inicio y el final. Para esta función, el final si se incluye

In [188]:
c = np.linspace(0, 100, 126)
c

array([  0. ,   0.8,   1.6,   2.4,   3.2,   4. ,   4.8,   5.6,   6.4,
         7.2,   8. ,   8.8,   9.6,  10.4,  11.2,  12. ,  12.8,  13.6,
        14.4,  15.2,  16. ,  16.8,  17.6,  18.4,  19.2,  20. ,  20.8,
        21.6,  22.4,  23.2,  24. ,  24.8,  25.6,  26.4,  27.2,  28. ,
        28.8,  29.6,  30.4,  31.2,  32. ,  32.8,  33.6,  34.4,  35.2,
        36. ,  36.8,  37.6,  38.4,  39.2,  40. ,  40.8,  41.6,  42.4,
        43.2,  44. ,  44.8,  45.6,  46.4,  47.2,  48. ,  48.8,  49.6,
        50.4,  51.2,  52. ,  52.8,  53.6,  54.4,  55.2,  56. ,  56.8,
        57.6,  58.4,  59.2,  60. ,  60.8,  61.6,  62.4,  63.2,  64. ,
        64.8,  65.6,  66.4,  67.2,  68. ,  68.8,  69.6,  70.4,  71.2,
        72. ,  72.8,  73.6,  74.4,  75.2,  76. ,  76.8,  77.6,  78.4,
        79.2,  80. ,  80.8,  81.6,  82.4,  83.2,  84. ,  84.8,  85.6,
        86.4,  87.2,  88. ,  88.8,  89.6,  90.4,  91.2,  92. ,  92.8,
        93.6,  94.4,  95.2,  96. ,  96.8,  97.6,  98.4,  99.2, 100. ])

Puede devolver el tamaño de paso si emplea la keyword `retstep`.

In [189]:
c, dx = np.linspace(0, 100, 126, retstep = True)
dx

np.float64(0.8)

Creación de matrices **Identidad** (Con 1s en una diagonal y 0s en todos lados)

In [190]:
identidad = np.eye(9)
identidad

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

Moviendo la diagonal

In [191]:
identidad = np.eye(9, k = 3)
identidad

array([[0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Empleando los generadores de números aleatorios. En este ejemplo, se genera el arreglo empleando una distribución normal, con promedio 0 y desviación estandar 1

In [192]:
n = np.random.normal(0, 1, 60)
n

array([-1.78680129, -0.55252668, -1.8977052 ,  1.56763514,  0.13345984,
        0.54814397, -0.96363145,  0.54807528, -1.42509069, -0.12808033,
       -0.84451638,  0.08453051, -0.94343558,  0.5391343 ,  1.04215591,
       -1.00696605,  0.17374205, -0.74807146,  0.85490627,  0.49519723,
        0.07557412, -0.54645486, -1.35210196,  1.05654566, -0.92923504,
        0.84226277,  0.17009704,  0.24674972, -1.00598077, -0.62158524,
        0.49132894,  3.38077521, -1.94649029, -0.01513922, -0.40787818,
       -0.73030754, -1.07384431, -0.35851241, -0.81677211,  0.7690674 ,
        2.01834722,  0.87147772, -1.38014083, -0.02118495,  0.57525567,
       -0.08627142,  0.12185402, -0.73191026,  1.17159808, -0.21427433,
       -0.48355691, -0.2591915 ,  0.7832603 ,  1.12159587,  0.83156674,
       -0.29889414, -1.60370983, -1.76110948, -0.9972465 ,  0.41327946])

## Diferencias entre listas de Python vs arreglos de Numpy


### Los arreglos solo pueden contener un solo tipo de dato

Listas. Pueden tener en sus entradas distintos tipos de datos sin ningún problema.

In [193]:
for i in [1, "a", []]:
    print(type(i))

<class 'int'>
<class 'str'>
<class 'list'>


Arreglos. Dado que solo pueden recibir un tipo de dato, y es imposible convertir de forma natural o lógica el texto a número, se convierte el número a su representación en carácter (string).

In [194]:
np.array([1, "a"])

array(['1', 'a'], dtype='<U21')

El `dtype = <U21` indica el tamaño máximo de los strings **unicode** que permite el arreglo. Para más información revisar la documentación [documentación dtype](https://numpy.org/doc/stable/reference/arrays.dtypes.html).

In [195]:
np.array([1, "abcdefghijklmnopqrstuvwxyz1234567890"])

array(['1', 'abcdefghijklmnopqrstuvwxyz1234567890'], dtype='<U36')

Al construirse con un string más grande, el dtype cambió a`dtype = <U36`.

### Para efectuar operaciones en las entradas de las listas se necesita forsozamente de un ciclo for, mientras que eso no es necesario para arreglos de Numpy

In [196]:
lista_prueba = list(range(5))
arreglo_prueba = np.arange(5)

print(f"Lista: {lista_prueba}\nArreglo: {arreglo_prueba}")

Lista: [0, 1, 2, 3, 4]
Arreglo: [0 1 2 3 4]


Listas

In [197]:
for i in range(len(lista_prueba)):
    lista_prueba[i] += 10

lista_prueba

[10, 11, 12, 13, 14]

Arreglos. Se puede sumar un número al arreglo y se realizará la suma entrada por entrada. Esta es una característica heredada de Matlab

In [198]:
arreglo_prueba += 10
arreglo_prueba

array([10, 11, 12, 13, 14])

### Los arreglos de Numpy pueden cambiar de forma

Para ello se emplea el método `reshaoe` el cual recibe una tupla.

In [199]:
d = np.linspace(1, 100, 100)
d

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [200]:
d = d.reshape((25, 4))
d

array([[  1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.],
       [  9.,  10.,  11.,  12.],
       [ 13.,  14.,  15.,  16.],
       [ 17.,  18.,  19.,  20.],
       [ 21.,  22.,  23.,  24.],
       [ 25.,  26.,  27.,  28.],
       [ 29.,  30.,  31.,  32.],
       [ 33.,  34.,  35.,  36.],
       [ 37.,  38.,  39.,  40.],
       [ 41.,  42.,  43.,  44.],
       [ 45.,  46.,  47.,  48.],
       [ 49.,  50.,  51.,  52.],
       [ 53.,  54.,  55.,  56.],
       [ 57.,  58.,  59.,  60.],
       [ 61.,  62.,  63.,  64.],
       [ 65.,  66.,  67.,  68.],
       [ 69.,  70.,  71.,  72.],
       [ 73.,  74.,  75.,  76.],
       [ 77.,  78.,  79.,  80.],
       [ 81.,  82.,  83.,  84.],
       [ 85.,  86.,  87.,  88.],
       [ 89.,  90.,  91.,  92.],
       [ 93.,  94.,  95.,  96.],
       [ 97.,  98.,  99., 100.]])

In [201]:
d = d.reshape((5, 5, 4))
d

array([[[  1.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.],
        [ 13.,  14.,  15.,  16.],
        [ 17.,  18.,  19.,  20.]],

       [[ 21.,  22.,  23.,  24.],
        [ 25.,  26.,  27.,  28.],
        [ 29.,  30.,  31.,  32.],
        [ 33.,  34.,  35.,  36.],
        [ 37.,  38.,  39.,  40.]],

       [[ 41.,  42.,  43.,  44.],
        [ 45.,  46.,  47.,  48.],
        [ 49.,  50.,  51.,  52.],
        [ 53.,  54.,  55.,  56.],
        [ 57.,  58.,  59.,  60.]],

       [[ 61.,  62.,  63.,  64.],
        [ 65.,  66.,  67.,  68.],
        [ 69.,  70.,  71.,  72.],
        [ 73.,  74.,  75.,  76.],
        [ 77.,  78.,  79.,  80.]],

       [[ 81.,  82.,  83.,  84.],
        [ 85.,  86.,  87.,  88.],
        [ 89.,  90.,  91.,  92.],
        [ 93.,  94.,  95.,  96.],
        [ 97.,  98.,  99., 100.]]])

## Guardar y cargar datos empleando un archivo `.csv`

### Función `.savetxt` para guardar datos

In [202]:
m = np.linspace(1, 100, 100)
m

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

Requiere el nombre del archivo que deseamos usar y el arreglo

In [203]:
np.savetxt("prueba1.csv", m)

Para un arreglo de distinta dimensión/forma

In [204]:
m = m.reshape((25, 4))
m

array([[  1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.],
       [  9.,  10.,  11.,  12.],
       [ 13.,  14.,  15.,  16.],
       [ 17.,  18.,  19.,  20.],
       [ 21.,  22.,  23.,  24.],
       [ 25.,  26.,  27.,  28.],
       [ 29.,  30.,  31.,  32.],
       [ 33.,  34.,  35.,  36.],
       [ 37.,  38.,  39.,  40.],
       [ 41.,  42.,  43.,  44.],
       [ 45.,  46.,  47.,  48.],
       [ 49.,  50.,  51.,  52.],
       [ 53.,  54.,  55.,  56.],
       [ 57.,  58.,  59.,  60.],
       [ 61.,  62.,  63.,  64.],
       [ 65.,  66.,  67.,  68.],
       [ 69.,  70.,  71.,  72.],
       [ 73.,  74.,  75.,  76.],
       [ 77.,  78.,  79.,  80.],
       [ 81.,  82.,  83.,  84.],
       [ 85.,  86.,  87.,  88.],
       [ 89.,  90.,  91.,  92.],
       [ 93.,  94.,  95.,  96.],
       [ 97.,  98.,  99., 100.]])

In [205]:
np.savetxt("prueba2.csv", m)