# Numpy

## Importación de bibliotecas

In [56]:
import numpy as np

## Creación de arreglos

### Manual


Creando primero una lista simple

In [57]:
a = np.array(list(range(10)))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Una lista de listas

In [58]:
a = np.array([[1, 2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

### Constructores

Arreglo de solo 1s. Recibe una tupla para definir su forma

In [59]:
b = np.ones((4, 8))
b

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

Arreglo de solo 0s. Recibe una tupla para definir su forma

In [60]:
b = np.zeros((6, 8))
b

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

Arreglo de datos vacíos. Importante por cuestiones de optimización. Recibe una tupla para definir su forma

In [61]:
b = np.empty((5, 3))
b

array([[1.35801824e-315, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 6.32404027e-322]])

Arreglo creado por la función `.arange`. Similar a `range`, pero si acepta tamaños de paso decimal (de punto flotante)

In [62]:
c = np.arange(0, 101, 2.5)
c

array([  0. ,   2.5,   5. ,   7.5,  10. ,  12.5,  15. ,  17.5,  20. ,
        22.5,  25. ,  27.5,  30. ,  32.5,  35. ,  37.5,  40. ,  42.5,
        45. ,  47.5,  50. ,  52.5,  55. ,  57.5,  60. ,  62.5,  65. ,
        67.5,  70. ,  72.5,  75. ,  77.5,  80. ,  82.5,  85. ,  87.5,
        90. ,  92.5,  95. ,  97.5, 100. ])

Arreglo creado por la función `.linspace`. En lugar de recibir el tamaño de paso, recibe cuantos valores quieres entre el inicio y el final. Para esta función, el final si se incluye

In [63]:
c = np.linspace(0, 100, 126)
c

array([  0. ,   0.8,   1.6,   2.4,   3.2,   4. ,   4.8,   5.6,   6.4,
         7.2,   8. ,   8.8,   9.6,  10.4,  11.2,  12. ,  12.8,  13.6,
        14.4,  15.2,  16. ,  16.8,  17.6,  18.4,  19.2,  20. ,  20.8,
        21.6,  22.4,  23.2,  24. ,  24.8,  25.6,  26.4,  27.2,  28. ,
        28.8,  29.6,  30.4,  31.2,  32. ,  32.8,  33.6,  34.4,  35.2,
        36. ,  36.8,  37.6,  38.4,  39.2,  40. ,  40.8,  41.6,  42.4,
        43.2,  44. ,  44.8,  45.6,  46.4,  47.2,  48. ,  48.8,  49.6,
        50.4,  51.2,  52. ,  52.8,  53.6,  54.4,  55.2,  56. ,  56.8,
        57.6,  58.4,  59.2,  60. ,  60.8,  61.6,  62.4,  63.2,  64. ,
        64.8,  65.6,  66.4,  67.2,  68. ,  68.8,  69.6,  70.4,  71.2,
        72. ,  72.8,  73.6,  74.4,  75.2,  76. ,  76.8,  77.6,  78.4,
        79.2,  80. ,  80.8,  81.6,  82.4,  83.2,  84. ,  84.8,  85.6,
        86.4,  87.2,  88. ,  88.8,  89.6,  90.4,  91.2,  92. ,  92.8,
        93.6,  94.4,  95.2,  96. ,  96.8,  97.6,  98.4,  99.2, 100. ])

Puede devolver el tamaño de paso si emplea la keyword `retstep`.

In [64]:
c, dx = np.linspace(0, 100, 126, retstep = True)
dx

np.float64(0.8)

Creación de matrices **Identidad** (Con 1s en una diagonal y 0s en todos lados)

In [65]:
identidad = np.eye(9)
identidad

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

Moviendo la diagonal

In [66]:
identidad = np.eye(9, k = 3)
identidad

array([[0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Empleando los generadores de números aleatorios. En este ejemplo, se genera el arreglo empleando una distribución normal, con promedio 0 y desviación estandar 1

In [67]:
n = np.random.normal(0, 1, 60)
n

array([ 0.050551  ,  0.4605856 , -2.19568198, -0.43056271,  1.14112887,
       -0.89734939,  0.7654064 , -0.05761355,  0.07518264,  1.92175833,
       -0.53047078,  0.30396541,  0.67342047,  0.42023027, -0.9083567 ,
        0.963525  , -1.44214475, -0.34689993,  1.07952006,  0.9095047 ,
        0.01793714,  1.32761066,  1.25560431,  0.15833724,  1.53898064,
       -0.41632727,  0.91285287,  0.98437148, -0.10746681,  2.30666552,
        1.29735977,  1.82506548, -0.22621261, -0.30238509, -0.5590947 ,
        1.52291324, -1.53787581,  1.44172827,  0.83541868, -1.01068716,
        0.30372321, -0.91286962, -1.95581344,  1.85824422, -1.1421145 ,
       -0.09947104,  0.07671491,  0.74868726, -1.8228902 , -1.46188876,
        1.80510054,  0.09233551,  0.54657338,  1.82591091,  0.57028194,
        0.31320376, -0.8118893 ,  0.19790902,  1.17053365,  0.34254858])

## Diferencia principal entre listas de Python vs arreglos de Numpy


### Los arreglos solo pueden contener un solo tipo de dato

Listas. Pueden tener en sus entradas distintos tipos de datos sin ningún problema.

In [68]:
for i in [1, "a", []]:
    print(type(i))

<class 'int'>
<class 'str'>
<class 'list'>


Arreglos. Dado que solo pueden recibir un tipo de dato, y es imposible convertir de forma natural o lógica el texto a número, por tanto, se convierte el número a su representación en carácter (string).

In [69]:
np.array([1, "a"])

array(['1', 'a'], dtype='<U21')

### Para efectuar operaciones en las entradas de las listas se necesita forsozamente de un ciclo for, mientras que eso no es necesario para arreglos de Numpy

In [70]:
lista_prueba = list(range(5))
arreglo_prueba = np.arange(5)

print(f"Lista: {lista_prueba}\nArreglo: {arreglo_prueba}")

Lista: [0, 1, 2, 3, 4]
Arreglo: [0 1 2 3 4]


Listas

In [71]:
for i in range(len(lista_prueba)):
    lista_prueba[i] += 10

lista_prueba

[10, 11, 12, 13, 14]

Arreglos. Se puede sumar un número al arreglo y se realizará la suma entrada por entrada. Esta es una característica heredada de Matlab

In [72]:
arreglo_prueba += 10
arreglo_prueba

array([10, 11, 12, 13, 14])

### Los arreglos de Numpy pueden cambiar de forma

In [74]:
d = np.linspace(1, 100, 100)
d

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [76]:
d = d.reshape((25, 4))
d

array([[  1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.],
       [  9.,  10.,  11.,  12.],
       [ 13.,  14.,  15.,  16.],
       [ 17.,  18.,  19.,  20.],
       [ 21.,  22.,  23.,  24.],
       [ 25.,  26.,  27.,  28.],
       [ 29.,  30.,  31.,  32.],
       [ 33.,  34.,  35.,  36.],
       [ 37.,  38.,  39.,  40.],
       [ 41.,  42.,  43.,  44.],
       [ 45.,  46.,  47.,  48.],
       [ 49.,  50.,  51.,  52.],
       [ 53.,  54.,  55.,  56.],
       [ 57.,  58.,  59.,  60.],
       [ 61.,  62.,  63.,  64.],
       [ 65.,  66.,  67.,  68.],
       [ 69.,  70.,  71.,  72.],
       [ 73.,  74.,  75.,  76.],
       [ 77.,  78.,  79.,  80.],
       [ 81.,  82.,  83.,  84.],
       [ 85.,  86.,  87.,  88.],
       [ 89.,  90.,  91.,  92.],
       [ 93.,  94.,  95.,  96.],
       [ 97.,  98.,  99., 100.]])

In [77]:
d = d.reshape((5, 5, 4))
d

array([[[  1.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.],
        [ 13.,  14.,  15.,  16.],
        [ 17.,  18.,  19.,  20.]],

       [[ 21.,  22.,  23.,  24.],
        [ 25.,  26.,  27.,  28.],
        [ 29.,  30.,  31.,  32.],
        [ 33.,  34.,  35.,  36.],
        [ 37.,  38.,  39.,  40.]],

       [[ 41.,  42.,  43.,  44.],
        [ 45.,  46.,  47.,  48.],
        [ 49.,  50.,  51.,  52.],
        [ 53.,  54.,  55.,  56.],
        [ 57.,  58.,  59.,  60.]],

       [[ 61.,  62.,  63.,  64.],
        [ 65.,  66.,  67.,  68.],
        [ 69.,  70.,  71.,  72.],
        [ 73.,  74.,  75.,  76.],
        [ 77.,  78.,  79.,  80.]],

       [[ 81.,  82.,  83.,  84.],
        [ 85.,  86.,  87.,  88.],
        [ 89.,  90.,  91.,  92.],
        [ 93.,  94.,  95.,  96.],
        [ 97.,  98.,  99., 100.]]])