# Más Numpy y Scipy

## Importación de bibliotecas

In [27]:
import numpy as np
from scipy import linalg

## Funciones de agregación

### Sumatoria

In [28]:
a = np.linspace(1, 100, 100).reshape((25, 4))
a

array([[  1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.],
       [  9.,  10.,  11.,  12.],
       [ 13.,  14.,  15.,  16.],
       [ 17.,  18.,  19.,  20.],
       [ 21.,  22.,  23.,  24.],
       [ 25.,  26.,  27.,  28.],
       [ 29.,  30.,  31.,  32.],
       [ 33.,  34.,  35.,  36.],
       [ 37.,  38.,  39.,  40.],
       [ 41.,  42.,  43.,  44.],
       [ 45.,  46.,  47.,  48.],
       [ 49.,  50.,  51.,  52.],
       [ 53.,  54.,  55.,  56.],
       [ 57.,  58.,  59.,  60.],
       [ 61.,  62.,  63.,  64.],
       [ 65.,  66.,  67.,  68.],
       [ 69.,  70.,  71.,  72.],
       [ 73.,  74.,  75.,  76.],
       [ 77.,  78.,  79.,  80.],
       [ 81.,  82.,  83.,  84.],
       [ 85.,  86.,  87.,  88.],
       [ 89.,  90.,  91.,  92.],
       [ 93.,  94.,  95.,  96.],
       [ 97.,  98.,  99., 100.]])

In [29]:
a.sum()

np.float64(5050.0)

In [30]:
a.sum(axis = 0)

array([1225., 1250., 1275., 1300.])

In [31]:
a.sum(axis = 1)

array([ 10.,  26.,  42.,  58.,  74.,  90., 106., 122., 138., 154., 170.,
       186., 202., 218., 234., 250., 266., 282., 298., 314., 330., 346.,
       362., 378., 394.])

### Promedio

In [32]:
a.mean()

np.float64(50.5)

In [33]:
a.mean(axis = 0)

array([49., 50., 51., 52.])

In [34]:
a.mean(axis = 1)

array([ 2.5,  6.5, 10.5, 14.5, 18.5, 22.5, 26.5, 30.5, 34.5, 38.5, 42.5,
       46.5, 50.5, 54.5, 58.5, 62.5, 66.5, 70.5, 74.5, 78.5, 82.5, 86.5,
       90.5, 94.5, 98.5])

### Desviación estándar

In [35]:
a.std()

np.float64(28.86607004772212)

In [36]:
a.std(axis = 0)

array([28.8444102, 28.8444102, 28.8444102, 28.8444102])

In [37]:
a.std(axis = 1)

array([1.11803399, 1.11803399, 1.11803399, 1.11803399, 1.11803399,
       1.11803399, 1.11803399, 1.11803399, 1.11803399, 1.11803399,
       1.11803399, 1.11803399, 1.11803399, 1.11803399, 1.11803399,
       1.11803399, 1.11803399, 1.11803399, 1.11803399, 1.11803399,
       1.11803399, 1.11803399, 1.11803399, 1.11803399, 1.11803399])

### Varianza

In [38]:
a.var()

np.float64(833.25)

In [39]:
a.var(axis = 0)

array([832., 832., 832., 832.])

In [40]:
a.var(axis = 1)

array([1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25,
       1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25,
       1.25, 1.25, 1.25])

### Valor máximo

In [41]:
np.random.seed(50)

In [42]:
b = np.random.normal(0, 1, 100).reshape((25, 4))
b

array([[-1.56035211, -0.0309776 , -0.62092842, -1.46458049],
       [ 1.41194612, -0.47673214, -0.78046921,  1.07026774],
       [-1.2822926 , -1.3274789 ,  0.12633764,  0.86219372],
       [ 0.69673696, -0.33456518, -0.99752606,  1.59890829],
       [ 3.31407535,  0.98777046,  0.12386626,  0.74278539],
       [-0.39395585,  0.14811582, -0.41223445, -0.16071506],
       [ 0.13953147,  0.28546937, -0.28126199,  1.71090732],
       [-0.14976664,  0.69030672,  1.09520951,  1.3384087 ],
       [-1.36898167,  0.48642763,  0.75352168,  0.36346459],
       [-0.31471048,  1.37328117, -0.62441716,  0.375754  ],
       [-0.20041632,  0.74303806,  0.85736196, -1.50618929],
       [-1.66635217, -0.2189948 , -0.35885843,  0.37852769],
       [ 0.68421537, -1.16785607, -0.79321662, -0.0388354 ],
       [ 2.70525499, -1.49138851,  0.09597793,  0.52468671],
       [ 0.8156655 ,  0.0515058 , -0.16455536,  0.27819942],
       [ 0.0871147 ,  0.03426837,  0.74656892, -0.94363758],
       [-0.24577667,  1.

In [43]:
b.max()

np.float64(3.3140753455120797)

In [44]:
b.max(axis = 0)

array([3.31407535, 1.62174549, 1.52166225, 1.71090732])

In [45]:
b.max(axis = 1)

array([-0.0309776 ,  1.41194612,  0.86219372,  1.59890829,  3.31407535,
        0.14811582,  1.71090732,  1.3384087 ,  0.75352168,  1.37328117,
        0.85736196,  0.37852769,  0.68421537,  2.70525499,  0.8156655 ,
        0.74656892,  1.10812096,  0.2518136 ,  1.47100167,  2.06581949,
        1.2308855 ,  0.35043074,  0.13751474,  1.62174549,  0.86642487])

### Valor mínimo

In [46]:
b.min()

np.float64(-3.809890377851563)

In [47]:
b.min(axis = 0)

array([-1.66635217, -2.57091976, -0.99752606, -3.80989038])

In [48]:
b.min(axis = 1)

array([-1.56035211, -0.78046921, -1.3274789 , -0.99752606,  0.12386626,
       -0.41223445, -0.28126199, -0.14976664, -1.36898167, -0.62441716,
       -1.50618929, -1.66635217, -1.16785607, -1.49138851, -0.16455536,
       -0.94363758, -0.24577667, -0.89095461, -0.58261947, -1.58788484,
       -3.80989038, -0.63428108, -2.57091976, -1.30677343, -0.8897683 ])

## Ordenar un arreglo

In [49]:
b.ravel()

array([-1.56035211, -0.0309776 , -0.62092842, -1.46458049,  1.41194612,
       -0.47673214, -0.78046921,  1.07026774, -1.2822926 , -1.3274789 ,
        0.12633764,  0.86219372,  0.69673696, -0.33456518, -0.99752606,
        1.59890829,  3.31407535,  0.98777046,  0.12386626,  0.74278539,
       -0.39395585,  0.14811582, -0.41223445, -0.16071506,  0.13953147,
        0.28546937, -0.28126199,  1.71090732, -0.14976664,  0.69030672,
        1.09520951,  1.3384087 , -1.36898167,  0.48642763,  0.75352168,
        0.36346459, -0.31471048,  1.37328117, -0.62441716,  0.375754  ,
       -0.20041632,  0.74303806,  0.85736196, -1.50618929, -1.66635217,
       -0.2189948 , -0.35885843,  0.37852769,  0.68421537, -1.16785607,
       -0.79321662, -0.0388354 ,  2.70525499, -1.49138851,  0.09597793,
        0.52468671,  0.8156655 ,  0.0515058 , -0.16455536,  0.27819942,
        0.0871147 ,  0.03426837,  0.74656892, -0.94363758, -0.24577667,
        1.10812096,  0.03900789, -0.21326669, -0.89095461, -0.27

In [63]:
np.sort(b.ravel())

array([-3.80989038, -2.57091976, -2.37345338, -1.66635217, -1.58788484,
       -1.56035211, -1.50618929, -1.49138851, -1.46458049, -1.36898167,
       -1.3274789 , -1.30677343, -1.2822926 , -1.16785607, -0.99752606,
       -0.94363758, -0.89095461, -0.8897683 , -0.79321662, -0.78046921,
       -0.71929619, -0.63428108, -0.62441716, -0.62092842, -0.58261947,
       -0.53553558, -0.47673214, -0.41223445, -0.39395585, -0.36293111,
       -0.35885843, -0.33456518, -0.31471048, -0.28126199, -0.27064634,
       -0.24577667, -0.2189948 , -0.21326669, -0.20041632, -0.19904969,
       -0.16455536, -0.16071506, -0.14976664, -0.05255078, -0.0388354 ,
       -0.03111097, -0.0309776 ,  0.00526774,  0.03426837,  0.03900789,
        0.0515058 ,  0.0871147 ,  0.09597793,  0.12386626,  0.12633764,
        0.13751474,  0.13953147,  0.14811582,  0.22224372,  0.2518136 ,
        0.27819942,  0.28546937,  0.35043074,  0.36346459,  0.375754  ,
        0.37852769,  0.48642763,  0.49398983,  0.52468671,  0.68

In [64]:
np.sort(b, axis = 0)

array([[-1.66635217, -2.57091976, -0.99752606, -3.80989038],
       [-1.56035211, -2.37345338, -0.79321662, -1.58788484],
       [-1.36898167, -1.49138851, -0.78046921, -1.50618929],
       [-1.2822926 , -1.3274789 , -0.62441716, -1.46458049],
       [-0.89095461, -1.16785607, -0.62092842, -1.30677343],
       [-0.8897683 , -0.47673214, -0.41223445, -0.94363758],
       [-0.39395585, -0.33456518, -0.35885843, -0.71929619],
       [-0.36293111, -0.27064634, -0.28126199, -0.63428108],
       [-0.31471048, -0.2189948 , -0.16455536, -0.58261947],
       [-0.24577667, -0.0309776 , -0.05255078, -0.53553558],
       [-0.20041632,  0.00526774, -0.03111097, -0.21326669],
       [-0.19904969,  0.03426837,  0.03900789, -0.16071506],
       [-0.14976664,  0.0515058 ,  0.09597793, -0.0388354 ],
       [ 0.0871147 ,  0.14811582,  0.12386626,  0.2518136 ],
       [ 0.13953147,  0.28546937,  0.12633764,  0.27819942],
       [ 0.68421537,  0.35043074,  0.13751474,  0.36346459],
       [ 0.69673696,  0.

In [65]:
np.sort(b, axis = 1)

array([[-1.56035211, -1.46458049, -0.62092842, -0.0309776 ],
       [-0.78046921, -0.47673214,  1.07026774,  1.41194612],
       [-1.3274789 , -1.2822926 ,  0.12633764,  0.86219372],
       [-0.99752606, -0.33456518,  0.69673696,  1.59890829],
       [ 0.12386626,  0.74278539,  0.98777046,  3.31407535],
       [-0.41223445, -0.39395585, -0.16071506,  0.14811582],
       [-0.28126199,  0.13953147,  0.28546937,  1.71090732],
       [-0.14976664,  0.69030672,  1.09520951,  1.3384087 ],
       [-1.36898167,  0.36346459,  0.48642763,  0.75352168],
       [-0.62441716, -0.31471048,  0.375754  ,  1.37328117],
       [-1.50618929, -0.20041632,  0.74303806,  0.85736196],
       [-1.66635217, -0.35885843, -0.2189948 ,  0.37852769],
       [-1.16785607, -0.79321662, -0.0388354 ,  0.68421537],
       [-1.49138851,  0.09597793,  0.52468671,  2.70525499],
       [-0.16455536,  0.0515058 ,  0.27819942,  0.8156655 ],
       [-0.94363758,  0.03426837,  0.0871147 ,  0.74656892],
       [-0.24577667, -0.