# Más Numpy y Scipy

## Importación de bibliotecas

In [76]:
import numpy as np
from scipy import linalg

## Funciones de agregación

### Sumatoria

In [77]:
a = np.linspace(1, 100, 100).reshape((25, 4))
a

array([[  1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.],
       [  9.,  10.,  11.,  12.],
       [ 13.,  14.,  15.,  16.],
       [ 17.,  18.,  19.,  20.],
       [ 21.,  22.,  23.,  24.],
       [ 25.,  26.,  27.,  28.],
       [ 29.,  30.,  31.,  32.],
       [ 33.,  34.,  35.,  36.],
       [ 37.,  38.,  39.,  40.],
       [ 41.,  42.,  43.,  44.],
       [ 45.,  46.,  47.,  48.],
       [ 49.,  50.,  51.,  52.],
       [ 53.,  54.,  55.,  56.],
       [ 57.,  58.,  59.,  60.],
       [ 61.,  62.,  63.,  64.],
       [ 65.,  66.,  67.,  68.],
       [ 69.,  70.,  71.,  72.],
       [ 73.,  74.,  75.,  76.],
       [ 77.,  78.,  79.,  80.],
       [ 81.,  82.,  83.,  84.],
       [ 85.,  86.,  87.,  88.],
       [ 89.,  90.,  91.,  92.],
       [ 93.,  94.,  95.,  96.],
       [ 97.,  98.,  99., 100.]])

In [78]:
a.sum()

np.float64(5050.0)

In [79]:
a.sum(axis = 0)

array([1225., 1250., 1275., 1300.])

In [80]:
a.sum(axis = 1)

array([ 10.,  26.,  42.,  58.,  74.,  90., 106., 122., 138., 154., 170.,
       186., 202., 218., 234., 250., 266., 282., 298., 314., 330., 346.,
       362., 378., 394.])

### Promedio

In [81]:
a.mean()

np.float64(50.5)

In [82]:
a.mean(axis = 0)

array([49., 50., 51., 52.])

In [83]:
a.mean(axis = 1)

array([ 2.5,  6.5, 10.5, 14.5, 18.5, 22.5, 26.5, 30.5, 34.5, 38.5, 42.5,
       46.5, 50.5, 54.5, 58.5, 62.5, 66.5, 70.5, 74.5, 78.5, 82.5, 86.5,
       90.5, 94.5, 98.5])

### Desviación estándar

In [84]:
a.std()

np.float64(28.86607004772212)

In [85]:
a.std(axis = 0)

array([28.8444102, 28.8444102, 28.8444102, 28.8444102])

In [86]:
a.std(axis = 1)

array([1.11803399, 1.11803399, 1.11803399, 1.11803399, 1.11803399,
       1.11803399, 1.11803399, 1.11803399, 1.11803399, 1.11803399,
       1.11803399, 1.11803399, 1.11803399, 1.11803399, 1.11803399,
       1.11803399, 1.11803399, 1.11803399, 1.11803399, 1.11803399,
       1.11803399, 1.11803399, 1.11803399, 1.11803399, 1.11803399])

### Varianza

In [87]:
a.var()

np.float64(833.25)

In [88]:
a.var(axis = 0)

array([832., 832., 832., 832.])

In [89]:
a.var(axis = 1)

array([1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25,
       1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25,
       1.25, 1.25, 1.25])

### Valor máximo

In [90]:
b = np.random.normal(0, 1, 100).reshape((25, 4))
b

array([[-1.75558083, -0.27351928, -1.72862712,  0.32444764],
       [-0.63132058,  0.89430148,  1.71581865, -0.1632551 ],
       [-1.03115481,  0.28632136,  1.904781  ,  0.84492259],
       [ 0.43020563,  1.11711491,  0.1456443 , -0.86753247],
       [ 0.97764269, -2.73737637, -0.69087206,  0.42085498],
       [-0.42379359,  0.25967385,  0.12673989,  1.68367899],
       [-1.02680203, -1.69962542, -0.7458462 , -1.3409285 ],
       [ 0.94127207, -1.36794295,  1.11810558, -0.03439715],
       [-0.54488604, -0.06052687, -1.52896324, -1.83845848],
       [-0.90617184,  0.40343476,  1.44942608,  0.28398745],
       [ 0.20576736,  1.7712903 ,  1.19103163, -0.76903993],
       [-0.63459474,  0.55876575, -0.16591259,  0.980544  ],
       [ 1.01779049,  0.42704467,  1.43793811, -2.3001932 ],
       [-2.63335977,  0.20269687, -0.94202067,  0.44836963],
       [ 1.28820752, -0.49308005, -0.25557966,  0.01953921],
       [-0.96138974,  0.90267632, -0.08166709, -0.60013995],
       [-0.01872124,  0.

In [91]:
b.max()

np.float64(1.9047809998590703)

In [92]:
b.max(axis = 0)

array([1.43808695, 1.7712903 , 1.904781  , 1.68367899])

In [93]:
b.max(axis = 1)

array([ 0.32444764,  1.71581865,  1.904781  ,  1.11711491,  0.97764269,
        1.68367899, -0.7458462 ,  1.11810558, -0.06052687,  1.44942608,
        1.7712903 ,  0.980544  ,  1.43793811,  0.44836963,  1.28820752,
        0.90267632,  1.55177992,  1.1122411 ,  1.02460753,  0.81493176,
        0.66455027,  1.43808695,  0.91665286,  1.39694762,  1.10572058])

### Valor mínimo

In [94]:
b.min()

np.float64(-2.737376374223853)

In [95]:
b.min(axis = 0)

array([-2.63335977, -2.73737637, -1.72862712, -2.3001932 ])

In [96]:
b.min(axis = 1)

array([-1.75558083, -0.63132058, -1.03115481, -0.86753247, -2.73737637,
       -0.42379359, -1.69962542, -1.36794295, -1.83845848, -0.90617184,
       -0.76903993, -0.63459474, -2.3001932 , -2.63335977, -0.49308005,
       -0.96138974, -0.52314436, -1.24179828, -1.38539053, -0.99146226,
       -1.61923389, -0.67951152, -1.22212284,  0.29931771,  0.43751411])

## Ordenar un arreglo

In [97]:
b.ravel()

array([-1.75558083, -0.27351928, -1.72862712,  0.32444764, -0.63132058,
        0.89430148,  1.71581865, -0.1632551 , -1.03115481,  0.28632136,
        1.904781  ,  0.84492259,  0.43020563,  1.11711491,  0.1456443 ,
       -0.86753247,  0.97764269, -2.73737637, -0.69087206,  0.42085498,
       -0.42379359,  0.25967385,  0.12673989,  1.68367899, -1.02680203,
       -1.69962542, -0.7458462 , -1.3409285 ,  0.94127207, -1.36794295,
        1.11810558, -0.03439715, -0.54488604, -0.06052687, -1.52896324,
       -1.83845848, -0.90617184,  0.40343476,  1.44942608,  0.28398745,
        0.20576736,  1.7712903 ,  1.19103163, -0.76903993, -0.63459474,
        0.55876575, -0.16591259,  0.980544  ,  1.01779049,  0.42704467,
        1.43793811, -2.3001932 , -2.63335977,  0.20269687, -0.94202067,
        0.44836963,  1.28820752, -0.49308005, -0.25557966,  0.01953921,
       -0.96138974,  0.90267632, -0.08166709, -0.60013995, -0.01872124,
        0.59379269, -0.52314436,  1.55177992,  0.56622663, -1.24

In [98]:
np.sort(b.ravel())

array([-2.73737637, -2.63335977, -2.3001932 , -1.83845848, -1.75558083,
       -1.72862712, -1.69962542, -1.61923389, -1.52896324, -1.38539053,
       -1.36794295, -1.3409285 , -1.24179828, -1.22212284, -1.17913308,
       -1.03115481, -1.02680203, -0.99146226, -0.96138974, -0.94202067,
       -0.90617184, -0.88886426, -0.86753247, -0.81999786, -0.76903993,
       -0.7458462 , -0.69087206, -0.67951152, -0.63459474, -0.63132058,
       -0.60013995, -0.54488604, -0.52314436, -0.49308005, -0.42379359,
       -0.27351928, -0.25557966, -0.16591259, -0.1632551 , -0.08166709,
       -0.06745456, -0.06052687, -0.03439715, -0.01872124,  0.01953921,
        0.02302814,  0.06777162,  0.12673989,  0.1456443 ,  0.20269687,
        0.20576736,  0.22648709,  0.25967385,  0.28398745,  0.28632136,
        0.287119  ,  0.28816047,  0.29931771,  0.32444764,  0.40343476,
        0.42085498,  0.42704467,  0.43020563,  0.43751411,  0.44836963,
        0.48144067,  0.55876575,  0.56622663,  0.59379269,  0.59

In [99]:
np.sort(b, axis = 0)

array([[-2.63335977, -2.73737637, -1.72862712, -2.3001932 ],
       [-1.75558083, -1.69962542, -1.52896324, -1.83845848],
       [-1.61923389, -1.36794295, -1.17913308, -1.3409285 ],
       [-1.38539053, -1.24179828, -0.99146226, -0.86753247],
       [-1.03115481, -1.22212284, -0.94202067, -0.76903993],
       [-1.02680203, -0.81999786, -0.7458462 , -0.67951152],
       [-0.96138974, -0.49308005, -0.69087206, -0.60013995],
       [-0.90617184, -0.27351928, -0.52314436, -0.1632551 ],
       [-0.88886426, -0.06052687, -0.25557966, -0.03439715],
       [-0.63459474,  0.20269687, -0.16591259,  0.01953921],
       [-0.63132058,  0.25967385, -0.08166709,  0.28398745],
       [-0.54488604,  0.28632136,  0.02302814,  0.32444764],
       [-0.42379359,  0.28816047,  0.06777162,  0.42085498],
       [-0.06745456,  0.29931771,  0.12673989,  0.43751411],
       [-0.01872124,  0.40343476,  0.1456443 ,  0.44836963],
       [ 0.20576736,  0.42704467,  0.22648709,  0.66455027],
       [ 0.43020563,  0.

In [100]:
np.sort(b, axis = 1)

array([[-1.75558083, -1.72862712, -0.27351928,  0.32444764],
       [-0.63132058, -0.1632551 ,  0.89430148,  1.71581865],
       [-1.03115481,  0.28632136,  0.84492259,  1.904781  ],
       [-0.86753247,  0.1456443 ,  0.43020563,  1.11711491],
       [-2.73737637, -0.69087206,  0.42085498,  0.97764269],
       [-0.42379359,  0.12673989,  0.25967385,  1.68367899],
       [-1.69962542, -1.3409285 , -1.02680203, -0.7458462 ],
       [-1.36794295, -0.03439715,  0.94127207,  1.11810558],
       [-1.83845848, -1.52896324, -0.54488604, -0.06052687],
       [-0.90617184,  0.28398745,  0.40343476,  1.44942608],
       [-0.76903993,  0.20576736,  1.19103163,  1.7712903 ],
       [-0.63459474, -0.16591259,  0.55876575,  0.980544  ],
       [-2.3001932 ,  0.42704467,  1.01779049,  1.43793811],
       [-2.63335977, -0.94202067,  0.20269687,  0.44836963],
       [-0.49308005, -0.25557966,  0.01953921,  1.28820752],
       [-0.96138974, -0.60013995, -0.08166709,  0.90267632],
       [-0.52314436, -0.