# Numpy

## Importación de bibliotecas

In [2]:
import numpy as np

In [3]:
len([1, 2, [3, 4]])

3

In [4]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [5]:
a.shape

(3,)

In [6]:
a = np.array([[1, 2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
a.size

6

In [8]:
a.shape

(3, 2)

In [9]:
list(range(1, 10, 2))

[1, 3, 5, 7, 9]

In [10]:
a = np.arange(-100, 101, 2.5)
a

array([-100. ,  -97.5,  -95. ,  -92.5,  -90. ,  -87.5,  -85. ,  -82.5,
        -80. ,  -77.5,  -75. ,  -72.5,  -70. ,  -67.5,  -65. ,  -62.5,
        -60. ,  -57.5,  -55. ,  -52.5,  -50. ,  -47.5,  -45. ,  -42.5,
        -40. ,  -37.5,  -35. ,  -32.5,  -30. ,  -27.5,  -25. ,  -22.5,
        -20. ,  -17.5,  -15. ,  -12.5,  -10. ,   -7.5,   -5. ,   -2.5,
          0. ,    2.5,    5. ,    7.5,   10. ,   12.5,   15. ,   17.5,
         20. ,   22.5,   25. ,   27.5,   30. ,   32.5,   35. ,   37.5,
         40. ,   42.5,   45. ,   47.5,   50. ,   52.5,   55. ,   57.5,
         60. ,   62.5,   65. ,   67.5,   70. ,   72.5,   75. ,   77.5,
         80. ,   82.5,   85. ,   87.5,   90. ,   92.5,   95. ,   97.5,
        100. ])

In [11]:
for i in [1, "a"]:
    print(type(i))

<class 'int'>
<class 'str'>


In [12]:
a = np.array([1, "abcdefghijklmnopqrstuvwxyz01234567890"])
a

array(['1', 'abcdefghijklmnopqrstuvwxyz01234567890'], dtype='<U37')

In [45]:
lista_a = [1, 2, 3]
arreglo_a = np.array([1, 2, 3])

In [48]:
arreglo_a

array([1, 2, 3])

In [14]:
for i in range(len(lista_a)):
    lista_a[i] = lista_a[i] + 1

lista_a

[2, 3, 4]

In [47]:
lista_a = [i + 1 for i in lista_a]
lista_a

[2, 3, 4]

In [49]:
arreglo_a + 1

array([2, 3, 4])

In [50]:
matriz_a = np.array([[1, 2], [3, 4]])
matriz_a

array([[1, 2],
       [3, 4]])

In [51]:
matriz_a + 1

array([[2, 3],
       [4, 5]])

In [54]:
np.eye(10) * 100

array([[100.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0., 100.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0., 100.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0., 100.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0., 100.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0., 100.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0., 100.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0., 100.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 100.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 100.]])

In [56]:
np.ones((10, 10)) * np.pi

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
        3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
        3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
        3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
        3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
        3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
        3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
        3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.1415926

In [59]:
a = np.array([1, 2, 3])
b = np.ones((10, 10))
c = np.arange(1, 12, 1)
d, e = np.linspace(0, 100, 251, retstep = True)
d

array([  0. ,   0.4,   0.8,   1.2,   1.6,   2. ,   2.4,   2.8,   3.2,
         3.6,   4. ,   4.4,   4.8,   5.2,   5.6,   6. ,   6.4,   6.8,
         7.2,   7.6,   8. ,   8.4,   8.8,   9.2,   9.6,  10. ,  10.4,
        10.8,  11.2,  11.6,  12. ,  12.4,  12.8,  13.2,  13.6,  14. ,
        14.4,  14.8,  15.2,  15.6,  16. ,  16.4,  16.8,  17.2,  17.6,
        18. ,  18.4,  18.8,  19.2,  19.6,  20. ,  20.4,  20.8,  21.2,
        21.6,  22. ,  22.4,  22.8,  23.2,  23.6,  24. ,  24.4,  24.8,
        25.2,  25.6,  26. ,  26.4,  26.8,  27.2,  27.6,  28. ,  28.4,
        28.8,  29.2,  29.6,  30. ,  30.4,  30.8,  31.2,  31.6,  32. ,
        32.4,  32.8,  33.2,  33.6,  34. ,  34.4,  34.8,  35.2,  35.6,
        36. ,  36.4,  36.8,  37.2,  37.6,  38. ,  38.4,  38.8,  39.2,
        39.6,  40. ,  40.4,  40.8,  41.2,  41.6,  42. ,  42.4,  42.8,
        43.2,  43.6,  44. ,  44.4,  44.8,  45.2,  45.6,  46. ,  46.4,
        46.8,  47.2,  47.6,  48. ,  48.4,  48.8,  49.2,  49.6,  50. ,
        50.4,  50.8,

In [60]:
e

np.float64(0.4)

In [62]:
g = np.zeros((12, 12, 3))
g

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
    

In [63]:
h = np.empty((3, 3, 3))
h

array([[[6.23581521e-316, 0.00000000e+000, 6.28988066e-310],
        [4.50856641e-317, 4.50680753e-317, 4.51022252e-317],
        [4.50745575e-317, 4.50982331e-317, 4.50725812e-317]],

       [[4.50959802e-317, 4.50672453e-317, 4.50825416e-317],
        [4.50809606e-317, 4.50696563e-317, 4.50851898e-317],
        [4.50743203e-317, 4.50718302e-317, 4.50907628e-317]],

       [[4.50904862e-317, 4.50990236e-317, 4.50776009e-317],
        [4.50712769e-317, 4.50968102e-317, 4.50686287e-317],
        [4.50643600e-317, 6.28987776e-310, 1.73911107e-321]]])

In [66]:
i = np.eye(10, k = -3)
i

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]])

In [21]:
l = np.linspace(0, 100, 351)
np.savetxt("prueba.csv", l)

In [67]:
m = np.loadtxt("prueba.csv")
m

array([  0.        ,   0.28571429,   0.57142857,   0.85714286,
         1.14285714,   1.42857143,   1.71428571,   2.        ,
         2.28571429,   2.57142857,   2.85714286,   3.14285714,
         3.42857143,   3.71428571,   4.        ,   4.28571429,
         4.57142857,   4.85714286,   5.14285714,   5.42857143,
         5.71428571,   6.        ,   6.28571429,   6.57142857,
         6.85714286,   7.14285714,   7.42857143,   7.71428571,
         8.        ,   8.28571429,   8.57142857,   8.85714286,
         9.14285714,   9.42857143,   9.71428571,  10.        ,
        10.28571429,  10.57142857,  10.85714286,  11.14285714,
        11.42857143,  11.71428571,  12.        ,  12.28571429,
        12.57142857,  12.85714286,  13.14285714,  13.42857143,
        13.71428571,  14.        ,  14.28571429,  14.57142857,
        14.85714286,  15.14285714,  15.42857143,  15.71428571,
        16.        ,  16.28571429,  16.57142857,  16.85714286,
        17.14285714,  17.42857143,  17.71428571,  18.  

In [71]:
n = np.linspace(1, 100, 100).reshape(((25, 4)))
n

array([[  1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.],
       [  9.,  10.,  11.,  12.],
       [ 13.,  14.,  15.,  16.],
       [ 17.,  18.,  19.,  20.],
       [ 21.,  22.,  23.,  24.],
       [ 25.,  26.,  27.,  28.],
       [ 29.,  30.,  31.,  32.],
       [ 33.,  34.,  35.,  36.],
       [ 37.,  38.,  39.,  40.],
       [ 41.,  42.,  43.,  44.],
       [ 45.,  46.,  47.,  48.],
       [ 49.,  50.,  51.,  52.],
       [ 53.,  54.,  55.,  56.],
       [ 57.,  58.,  59.,  60.],
       [ 61.,  62.,  63.,  64.],
       [ 65.,  66.,  67.,  68.],
       [ 69.,  70.,  71.,  72.],
       [ 73.,  74.,  75.,  76.],
       [ 77.,  78.,  79.,  80.],
       [ 81.,  82.,  83.,  84.],
       [ 85.,  86.,  87.,  88.],
       [ 89.,  90.,  91.,  92.],
       [ 93.,  94.,  95.,  96.],
       [ 97.,  98.,  99., 100.]])

In [72]:
np.savetxt("prueba2.csv", n)

In [75]:
p1, p2, p3, p4 = np.loadtxt("prueba2.csv", unpack = True)


In [76]:
p

array([[  1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.],
       [  9.,  10.,  11.,  12.],
       [ 13.,  14.,  15.,  16.],
       [ 17.,  18.,  19.,  20.],
       [ 21.,  22.,  23.,  24.],
       [ 25.,  26.,  27.,  28.],
       [ 29.,  30.,  31.,  32.],
       [ 33.,  34.,  35.,  36.],
       [ 37.,  38.,  39.,  40.],
       [ 41.,  42.,  43.,  44.],
       [ 45.,  46.,  47.,  48.],
       [ 49.,  50.,  51.,  52.],
       [ 53.,  54.,  55.,  56.],
       [ 57.,  58.,  59.,  60.],
       [ 61.,  62.,  63.,  64.],
       [ 65.,  66.,  67.,  68.],
       [ 69.,  70.,  71.,  72.],
       [ 73.,  74.,  75.,  76.],
       [ 77.,  78.,  79.,  80.],
       [ 81.,  82.,  83.,  84.],
       [ 85.,  86.,  87.,  88.],
       [ 89.,  90.,  91.,  92.],
       [ 93.,  94.,  95.,  96.],
       [ 97.,  98.,  99., 100.]])

In [77]:
p1

array([ 1.,  5.,  9., 13., 17., 21., 25., 29., 33., 37., 41., 45., 49.,
       53., 57., 61., 65., 69., 73., 77., 81., 85., 89., 93., 97.])

In [78]:
p2

array([ 2.,  6., 10., 14., 18., 22., 26., 30., 34., 38., 42., 46., 50.,
       54., 58., 62., 66., 70., 74., 78., 82., 86., 90., 94., 98.])

In [79]:
p3

array([ 3.,  7., 11., 15., 19., 23., 27., 31., 35., 39., 43., 47., 51.,
       55., 59., 63., 67., 71., 75., 79., 83., 87., 91., 95., 99.])

In [80]:
p4

array([  4.,   8.,  12.,  16.,  20.,  24.,  28.,  32.,  36.,  40.,  44.,
        48.,  52.,  56.,  60.,  64.,  68.,  72.,  76.,  80.,  84.,  88.,
        92.,  96., 100.])

In [81]:
x = np.linspace(0, 2 * np.pi, 121)
seno_x = np.sin(x)
seno_x

array([ 0.00000000e+00,  5.23359562e-02,  1.04528463e-01,  1.56434465e-01,
        2.07911691e-01,  2.58819045e-01,  3.09016994e-01,  3.58367950e-01,
        4.06736643e-01,  4.53990500e-01,  5.00000000e-01,  5.44639035e-01,
        5.87785252e-01,  6.29320391e-01,  6.69130606e-01,  7.07106781e-01,
        7.43144825e-01,  7.77145961e-01,  8.09016994e-01,  8.38670568e-01,
        8.66025404e-01,  8.91006524e-01,  9.13545458e-01,  9.33580426e-01,
        9.51056516e-01,  9.65925826e-01,  9.78147601e-01,  9.87688341e-01,
        9.94521895e-01,  9.98629535e-01,  1.00000000e+00,  9.98629535e-01,
        9.94521895e-01,  9.87688341e-01,  9.78147601e-01,  9.65925826e-01,
        9.51056516e-01,  9.33580426e-01,  9.13545458e-01,  8.91006524e-01,
        8.66025404e-01,  8.38670568e-01,  8.09016994e-01,  7.77145961e-01,
        7.43144825e-01,  7.07106781e-01,  6.69130606e-01,  6.29320391e-01,
        5.87785252e-01,  5.44639035e-01,  5.00000000e-01,  4.53990500e-01,
        4.06736643e-01,  

In [86]:
seno_x[90]

np.float64(-1.0)

In [ ]:
seno_x 

In [32]:
seno_x[seno_x >= 0]

array([0.00000000e+00, 5.23359562e-02, 1.04528463e-01, 1.56434465e-01,
       2.07911691e-01, 2.58819045e-01, 3.09016994e-01, 3.58367950e-01,
       4.06736643e-01, 4.53990500e-01, 5.00000000e-01, 5.44639035e-01,
       5.87785252e-01, 6.29320391e-01, 6.69130606e-01, 7.07106781e-01,
       7.43144825e-01, 7.77145961e-01, 8.09016994e-01, 8.38670568e-01,
       8.66025404e-01, 8.91006524e-01, 9.13545458e-01, 9.33580426e-01,
       9.51056516e-01, 9.65925826e-01, 9.78147601e-01, 9.87688341e-01,
       9.94521895e-01, 9.98629535e-01, 1.00000000e+00, 9.98629535e-01,
       9.94521895e-01, 9.87688341e-01, 9.78147601e-01, 9.65925826e-01,
       9.51056516e-01, 9.33580426e-01, 9.13545458e-01, 8.91006524e-01,
       8.66025404e-01, 8.38670568e-01, 8.09016994e-01, 7.77145961e-01,
       7.43144825e-01, 7.07106781e-01, 6.69130606e-01, 6.29320391e-01,
       5.87785252e-01, 5.44639035e-01, 5.00000000e-01, 4.53990500e-01,
       4.06736643e-01, 3.58367950e-01, 3.09016994e-01, 2.58819045e-01,
      

In [33]:
seno_x.size

121

In [34]:
seno_x[seno_x >= 0].size

61

In [35]:
cos_x = np.cos(x)
cos_x

array([ 1.00000000e+00,  9.98629535e-01,  9.94521895e-01,  9.87688341e-01,
        9.78147601e-01,  9.65925826e-01,  9.51056516e-01,  9.33580426e-01,
        9.13545458e-01,  8.91006524e-01,  8.66025404e-01,  8.38670568e-01,
        8.09016994e-01,  7.77145961e-01,  7.43144825e-01,  7.07106781e-01,
        6.69130606e-01,  6.29320391e-01,  5.87785252e-01,  5.44639035e-01,
        5.00000000e-01,  4.53990500e-01,  4.06736643e-01,  3.58367950e-01,
        3.09016994e-01,  2.58819045e-01,  2.07911691e-01,  1.56434465e-01,
        1.04528463e-01,  5.23359562e-02,  6.12323400e-17, -5.23359562e-02,
       -1.04528463e-01, -1.56434465e-01, -2.07911691e-01, -2.58819045e-01,
       -3.09016994e-01, -3.58367950e-01, -4.06736643e-01, -4.53990500e-01,
       -5.00000000e-01, -5.44639035e-01, -5.87785252e-01, -6.29320391e-01,
       -6.69130606e-01, -7.07106781e-01, -7.43144825e-01, -7.77145961e-01,
       -8.09016994e-01, -8.38670568e-01, -8.66025404e-01, -8.91006524e-01,
       -9.13545458e-01, -

In [36]:
cos_x[cos_x >= 0]

array([1.00000000e+00, 9.98629535e-01, 9.94521895e-01, 9.87688341e-01,
       9.78147601e-01, 9.65925826e-01, 9.51056516e-01, 9.33580426e-01,
       9.13545458e-01, 8.91006524e-01, 8.66025404e-01, 8.38670568e-01,
       8.09016994e-01, 7.77145961e-01, 7.43144825e-01, 7.07106781e-01,
       6.69130606e-01, 6.29320391e-01, 5.87785252e-01, 5.44639035e-01,
       5.00000000e-01, 4.53990500e-01, 4.06736643e-01, 3.58367950e-01,
       3.09016994e-01, 2.58819045e-01, 2.07911691e-01, 1.56434465e-01,
       1.04528463e-01, 5.23359562e-02, 6.12323400e-17, 5.23359562e-02,
       1.04528463e-01, 1.56434465e-01, 2.07911691e-01, 2.58819045e-01,
       3.09016994e-01, 3.58367950e-01, 4.06736643e-01, 4.53990500e-01,
       5.00000000e-01, 5.44639035e-01, 5.87785252e-01, 6.29320391e-01,
       6.69130606e-01, 7.07106781e-01, 7.43144825e-01, 7.77145961e-01,
       8.09016994e-01, 8.38670568e-01, 8.66025404e-01, 8.91006524e-01,
       9.13545458e-01, 9.33580426e-01, 9.51056516e-01, 9.65925826e-01,
      

In [37]:
cos_x >= 0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [38]:
a = np.random.normal(0, 1, 100)
a

array([-0.48041206,  0.13886095, -0.38764261,  0.53726309,  3.05615679,
       -0.77759477,  1.14204102, -0.40947731,  0.325823  ,  0.17925359,
        0.30925891,  0.21813192, -0.04754173, -2.03179174, -1.16939611,
        0.43452298,  1.00745953,  2.38519537, -0.62814598, -0.32590766,
        0.21712973,  1.58572863,  0.59581406, -0.80439979, -0.55981725,
        0.21105969,  0.37545144,  1.3003351 ,  0.20067765, -1.24856167,
        1.19284257,  1.40713026,  1.05860583, -0.9639237 , -0.26677205,
        0.89422797, -0.90293939, -1.58487158, -0.89277658,  0.50618458,
        0.3121855 , -0.44600423, -0.4923525 ,  0.9954854 ,  1.96188111,
        0.90557516,  2.70625311,  0.20641946, -1.12567814, -0.20008261,
        0.76559258, -0.54279183, -1.55254173, -0.53395102, -2.13529517,
       -0.53636269, -1.90140022,  0.88210314, -1.53073268,  1.69705885,
       -0.32739166, -1.56186789, -1.26992573,  0.12409161,  0.57349146,
        1.17533644, -0.34206523, -0.29380346, -0.59657633,  3.91

In [39]:
b = a > 0
b

array([False,  True, False,  True,  True, False,  True, False,  True,
        True,  True,  True, False, False, False,  True,  True,  True,
       False, False,  True,  True,  True, False, False,  True,  True,
        True,  True, False,  True,  True,  True, False, False,  True,
       False, False, False,  True,  True, False, False,  True,  True,
        True,  True,  True, False, False,  True, False, False, False,
       False, False, False,  True, False,  True, False, False, False,
        True,  True,  True, False, False, False,  True,  True, False,
       False,  True, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
       False])

In [40]:
a[b]

array([0.13886095, 0.53726309, 3.05615679, 1.14204102, 0.325823  ,
       0.17925359, 0.30925891, 0.21813192, 0.43452298, 1.00745953,
       2.38519537, 0.21712973, 1.58572863, 0.59581406, 0.21105969,
       0.37545144, 1.3003351 , 0.20067765, 1.19284257, 1.40713026,
       1.05860583, 0.89422797, 0.50618458, 0.3121855 , 0.9954854 ,
       1.96188111, 0.90557516, 2.70625311, 0.20641946, 0.76559258,
       0.88210314, 1.69705885, 0.12409161, 0.57349146, 1.17533644,
       3.91896339, 0.2933772 , 0.23837955, 0.10798682, 1.14059639,
       0.00967447, 0.24363464, 0.84520584, 1.86040486, 0.14336893,
       0.25320091, 0.25943078, 0.41701095, 0.1575127 , 1.05509608,
       1.10880647, 0.32063748, 0.40483523, 0.82568535, 0.42735816,
       0.41200667, 0.12058503])

In [41]:
a.reshape((25, 4)).sum(axis = 0)

array([-0.0686088 ,  5.77721826,  1.25476306,  3.66374046])

In [42]:
np.random.

SyntaxError: invalid syntax (393120376.py, line 1)