# Más Numpy y Scipy

## Importación de bibliotecas

In [161]:
import numpy as np
from scipy import linalg
from scipy import fft

#### Semilla 

In [162]:
np.random.seed(50)

## Funciones de agregación

### Sumatoria

In [163]:
a = np.linspace(1, 100, 100).reshape((25, 4))
a

array([[  1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.],
       [  9.,  10.,  11.,  12.],
       [ 13.,  14.,  15.,  16.],
       [ 17.,  18.,  19.,  20.],
       [ 21.,  22.,  23.,  24.],
       [ 25.,  26.,  27.,  28.],
       [ 29.,  30.,  31.,  32.],
       [ 33.,  34.,  35.,  36.],
       [ 37.,  38.,  39.,  40.],
       [ 41.,  42.,  43.,  44.],
       [ 45.,  46.,  47.,  48.],
       [ 49.,  50.,  51.,  52.],
       [ 53.,  54.,  55.,  56.],
       [ 57.,  58.,  59.,  60.],
       [ 61.,  62.,  63.,  64.],
       [ 65.,  66.,  67.,  68.],
       [ 69.,  70.,  71.,  72.],
       [ 73.,  74.,  75.,  76.],
       [ 77.,  78.,  79.,  80.],
       [ 81.,  82.,  83.,  84.],
       [ 85.,  86.,  87.,  88.],
       [ 89.,  90.,  91.,  92.],
       [ 93.,  94.,  95.,  96.],
       [ 97.,  98.,  99., 100.]])

In [164]:
a.sum()

np.float64(5050.0)

In [165]:
a.sum(axis = 0)

array([1225., 1250., 1275., 1300.])

In [166]:
a.sum(axis = 1)

array([ 10.,  26.,  42.,  58.,  74.,  90., 106., 122., 138., 154., 170.,
       186., 202., 218., 234., 250., 266., 282., 298., 314., 330., 346.,
       362., 378., 394.])

### Promedio

In [167]:
a.mean()

np.float64(50.5)

In [168]:
a.mean(axis = 0)

array([49., 50., 51., 52.])

In [169]:
a.mean(axis = 1)

array([ 2.5,  6.5, 10.5, 14.5, 18.5, 22.5, 26.5, 30.5, 34.5, 38.5, 42.5,
       46.5, 50.5, 54.5, 58.5, 62.5, 66.5, 70.5, 74.5, 78.5, 82.5, 86.5,
       90.5, 94.5, 98.5])

### Desviación estándar

In [170]:
a.std()

np.float64(28.86607004772212)

In [171]:
a.std(axis = 0)

array([28.8444102, 28.8444102, 28.8444102, 28.8444102])

In [172]:
a.std(axis = 1)

array([1.11803399, 1.11803399, 1.11803399, 1.11803399, 1.11803399,
       1.11803399, 1.11803399, 1.11803399, 1.11803399, 1.11803399,
       1.11803399, 1.11803399, 1.11803399, 1.11803399, 1.11803399,
       1.11803399, 1.11803399, 1.11803399, 1.11803399, 1.11803399,
       1.11803399, 1.11803399, 1.11803399, 1.11803399, 1.11803399])

### Varianza

In [173]:
a.var()

np.float64(833.25)

In [174]:
a.var(axis = 0)

array([832., 832., 832., 832.])

In [175]:
a.var(axis = 1)

array([1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25,
       1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 1.25,
       1.25, 1.25, 1.25])

### Valor máximo

In [176]:
b = np.random.normal(0, 1, 100).reshape((25, 4))
b

array([[-1.56035211, -0.0309776 , -0.62092842, -1.46458049],
       [ 1.41194612, -0.47673214, -0.78046921,  1.07026774],
       [-1.2822926 , -1.3274789 ,  0.12633764,  0.86219372],
       [ 0.69673696, -0.33456518, -0.99752606,  1.59890829],
       [ 3.31407535,  0.98777046,  0.12386626,  0.74278539],
       [-0.39395585,  0.14811582, -0.41223445, -0.16071506],
       [ 0.13953147,  0.28546937, -0.28126199,  1.71090732],
       [-0.14976664,  0.69030672,  1.09520951,  1.3384087 ],
       [-1.36898167,  0.48642763,  0.75352168,  0.36346459],
       [-0.31471048,  1.37328117, -0.62441716,  0.375754  ],
       [-0.20041632,  0.74303806,  0.85736196, -1.50618929],
       [-1.66635217, -0.2189948 , -0.35885843,  0.37852769],
       [ 0.68421537, -1.16785607, -0.79321662, -0.0388354 ],
       [ 2.70525499, -1.49138851,  0.09597793,  0.52468671],
       [ 0.8156655 ,  0.0515058 , -0.16455536,  0.27819942],
       [ 0.0871147 ,  0.03426837,  0.74656892, -0.94363758],
       [-0.24577667,  1.

In [177]:
b.max()

np.float64(3.3140753455120797)

In [178]:
b.max(axis = 0)

array([3.31407535, 1.62174549, 1.52166225, 1.71090732])

In [179]:
b.max(axis = 1)

array([-0.0309776 ,  1.41194612,  0.86219372,  1.59890829,  3.31407535,
        0.14811582,  1.71090732,  1.3384087 ,  0.75352168,  1.37328117,
        0.85736196,  0.37852769,  0.68421537,  2.70525499,  0.8156655 ,
        0.74656892,  1.10812096,  0.2518136 ,  1.47100167,  2.06581949,
        1.2308855 ,  0.35043074,  0.13751474,  1.62174549,  0.86642487])

### Valor mínimo

In [180]:
b.min()

np.float64(-3.809890377851563)

In [181]:
b.min(axis = 0)

array([-1.66635217, -2.57091976, -0.99752606, -3.80989038])

In [182]:
b.min(axis = 1)

array([-1.56035211, -0.78046921, -1.3274789 , -0.99752606,  0.12386626,
       -0.41223445, -0.28126199, -0.14976664, -1.36898167, -0.62441716,
       -1.50618929, -1.66635217, -1.16785607, -1.49138851, -0.16455536,
       -0.94363758, -0.24577667, -0.89095461, -0.58261947, -1.58788484,
       -3.80989038, -0.63428108, -2.57091976, -1.30677343, -0.8897683 ])

## Ordenar un arreglo

In [183]:
b.ravel()

array([-1.56035211, -0.0309776 , -0.62092842, -1.46458049,  1.41194612,
       -0.47673214, -0.78046921,  1.07026774, -1.2822926 , -1.3274789 ,
        0.12633764,  0.86219372,  0.69673696, -0.33456518, -0.99752606,
        1.59890829,  3.31407535,  0.98777046,  0.12386626,  0.74278539,
       -0.39395585,  0.14811582, -0.41223445, -0.16071506,  0.13953147,
        0.28546937, -0.28126199,  1.71090732, -0.14976664,  0.69030672,
        1.09520951,  1.3384087 , -1.36898167,  0.48642763,  0.75352168,
        0.36346459, -0.31471048,  1.37328117, -0.62441716,  0.375754  ,
       -0.20041632,  0.74303806,  0.85736196, -1.50618929, -1.66635217,
       -0.2189948 , -0.35885843,  0.37852769,  0.68421537, -1.16785607,
       -0.79321662, -0.0388354 ,  2.70525499, -1.49138851,  0.09597793,
        0.52468671,  0.8156655 ,  0.0515058 , -0.16455536,  0.27819942,
        0.0871147 ,  0.03426837,  0.74656892, -0.94363758, -0.24577667,
        1.10812096,  0.03900789, -0.21326669, -0.89095461, -0.27

In [184]:
b.ravel().shape

(100,)

In [185]:
np.sort(b.ravel())[:: -1]

array([ 3.31407535,  2.70525499,  2.06581949,  1.71090732,  1.62174549,
        1.59890829,  1.52166225,  1.47100167,  1.41194612,  1.37328117,
        1.3384087 ,  1.2308855 ,  1.10812096,  1.09520951,  1.08783389,
        1.07026774,  0.98777046,  0.86642487,  0.86219372,  0.85736196,
        0.8156655 ,  0.80518904,  0.75352168,  0.74656892,  0.74303806,
        0.74278539,  0.72852289,  0.70792609,  0.69673696,  0.69030672,
        0.68421537,  0.52468671,  0.49398983,  0.48642763,  0.37852769,
        0.375754  ,  0.36346459,  0.35043074,  0.28546937,  0.27819942,
        0.2518136 ,  0.22224372,  0.14811582,  0.13953147,  0.13751474,
        0.12633764,  0.12386626,  0.09597793,  0.0871147 ,  0.0515058 ,
        0.03900789,  0.03426837,  0.00526774, -0.0309776 , -0.03111097,
       -0.0388354 , -0.05255078, -0.14976664, -0.16071506, -0.16455536,
       -0.19904969, -0.20041632, -0.21326669, -0.2189948 , -0.24577667,
       -0.27064634, -0.28126199, -0.31471048, -0.33456518, -0.35

In [186]:
np.sort(b, axis = 0)

array([[-1.66635217, -2.57091976, -0.99752606, -3.80989038],
       [-1.56035211, -2.37345338, -0.79321662, -1.58788484],
       [-1.36898167, -1.49138851, -0.78046921, -1.50618929],
       [-1.2822926 , -1.3274789 , -0.62441716, -1.46458049],
       [-0.89095461, -1.16785607, -0.62092842, -1.30677343],
       [-0.8897683 , -0.47673214, -0.41223445, -0.94363758],
       [-0.39395585, -0.33456518, -0.35885843, -0.71929619],
       [-0.36293111, -0.27064634, -0.28126199, -0.63428108],
       [-0.31471048, -0.2189948 , -0.16455536, -0.58261947],
       [-0.24577667, -0.0309776 , -0.05255078, -0.53553558],
       [-0.20041632,  0.00526774, -0.03111097, -0.21326669],
       [-0.19904969,  0.03426837,  0.03900789, -0.16071506],
       [-0.14976664,  0.0515058 ,  0.09597793, -0.0388354 ],
       [ 0.0871147 ,  0.14811582,  0.12386626,  0.2518136 ],
       [ 0.13953147,  0.28546937,  0.12633764,  0.27819942],
       [ 0.68421537,  0.35043074,  0.13751474,  0.36346459],
       [ 0.69673696,  0.

In [187]:
np.sort(b, axis = 1)

array([[-1.56035211, -1.46458049, -0.62092842, -0.0309776 ],
       [-0.78046921, -0.47673214,  1.07026774,  1.41194612],
       [-1.3274789 , -1.2822926 ,  0.12633764,  0.86219372],
       [-0.99752606, -0.33456518,  0.69673696,  1.59890829],
       [ 0.12386626,  0.74278539,  0.98777046,  3.31407535],
       [-0.41223445, -0.39395585, -0.16071506,  0.14811582],
       [-0.28126199,  0.13953147,  0.28546937,  1.71090732],
       [-0.14976664,  0.69030672,  1.09520951,  1.3384087 ],
       [-1.36898167,  0.36346459,  0.48642763,  0.75352168],
       [-0.62441716, -0.31471048,  0.375754  ,  1.37328117],
       [-1.50618929, -0.20041632,  0.74303806,  0.85736196],
       [-1.66635217, -0.35885843, -0.2189948 ,  0.37852769],
       [-1.16785607, -0.79321662, -0.0388354 ,  0.68421537],
       [-1.49138851,  0.09597793,  0.52468671,  2.70525499],
       [-0.16455536,  0.0515058 ,  0.27819942,  0.8156655 ],
       [-0.94363758,  0.03426837,  0.0871147 ,  0.74656892],
       [-0.24577667, -0.

## Sistemas de ecuaciones (álgebra lineal)

Vamos a resolver el sistema 
$$3x + 1y + 0z = 2$$
$$2x - 1y + 5z = 4$$
$$0x + 0y + 1z = -1$$

$$3, 1, 0$$
$$2, -1, 5$$
$$0, 0, 1$$

$$2, 4, -1$$

In [188]:
a = np.array([[3, 2, 0], [1, -1, 0], [0, 5, 1]])
b = np.array([2, 4, -1])

Empleando el solucionador de `linalg`

In [189]:
sol = linalg.solve(a, b)
sol

array([ 2., -2.,  9.])

Comprobación

In [190]:
np.dot(a, sol) == b

array([ True,  True,  True])

In [191]:
np.dot(a, sol)

array([ 2.,  4., -1.])

In [192]:
b

array([ 2,  4, -1])

Vamos a resolver un sistema aleatorio

In [193]:
n = 20
a = np.random.randint(0, 20, size = (n, n))
b = np.random.randint(0, 20, size = n)

Empleando el solucionador de `linalg`

In [194]:
sol = linalg.solve(a, b)
sol

array([ 3.35385074,  0.22197981,  2.199477  , -2.5813922 ,  0.6589672 ,
        0.19442979, -1.19550212, -3.31502097,  4.30857631, -1.77919006,
       -1.26117744,  4.42169736,  1.66401103,  0.50272569, -0.55278959,
       -0.97939858, -0.81646333, -1.10084957, -4.73883399, -0.13471683])

Comprobación

In [195]:
np.dot(a, sol) == b

array([ True, False, False,  True, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [196]:
np.dot(a, sol)

array([ 1., 17.,  7., 12.,  8., 13., 14., 19., 13., 19., 14.,  2., 11.,
        7., 10.,  2., 18.,  3.,  5., 18.])

In [197]:
b

array([ 1, 17,  7, 12,  8, 13, 14, 19, 13, 19, 14,  2, 11,  7, 10,  2, 18,
        3,  5, 18])

¿Por qué salen dos `False`?

## Inversa de una matriz (álgebra lineal)

In [205]:
n = 49
a = np.random.randint(0, 20, size = n).reshape((7, 7))
a

array([[ 4,  0,  5, 15,  5,  7, 11],
       [ 3,  1,  7,  3, 14, 11,  7],
       [15, 19, 18,  5,  1,  7,  9],
       [15,  7, 14, 11,  7, 11, 16],
       [ 2, 10, 16, 14, 12,  6,  6],
       [ 5, 11, 17, 15,  0, 12,  4],
       [19, 17, 17, 13,  1,  8,  3]])

In [206]:
a_inv = linalg.inv(a)
a_inv

array([[-0.0433932 , -0.00927923, -0.06010273,  0.06720307, -0.01088846,
        -0.03209201,  0.06721802],
       [ 0.17730352,  0.07454315,  0.17807924, -0.2269569 , -0.0439107 ,
        -0.05058913,  0.0074257 ],
       [-0.22815099, -0.1008104 , -0.13345887,  0.23078826,  0.09266767,
         0.07343912, -0.04197035],
       [ 0.07503088, -0.01570839, -0.01532917, -0.04490759,  0.01159744,
        -0.00857745,  0.03527608],
       [ 0.01338231,  0.04912619, -0.00305774, -0.03421423,  0.0381263 ,
        -0.05899744,  0.03036349],
       [ 0.06470412,  0.10393664,  0.04454285, -0.09297847, -0.09800828,
         0.05605023,  0.00377228],
       [ 0.06082038, -0.01785388,  0.0764665 ,  0.00661643, -0.00893815,
        -0.01886638, -0.06967135]])

In [208]:
resultado = np.dot(a, a_inv)
resultado

array([[ 1.00000000e+00, -1.07552856e-16, -2.08166817e-16,
         4.96130914e-16,  1.45716772e-16,  1.87350135e-16,
         0.00000000e+00],
       [ 4.16333634e-17,  1.00000000e+00,  6.93889390e-17,
        -3.50414142e-16,  1.73472348e-16, -3.46944695e-17,
         2.77555756e-16],
       [ 6.93889390e-17,  9.36750677e-17,  1.00000000e+00,
         6.00214323e-16,  8.25728375e-16,  4.78783679e-16,
         1.11022302e-16],
       [ 2.22044605e-16,  3.33066907e-16,  2.22044605e-16,
         1.00000000e+00,  4.44089210e-16,  1.66533454e-16,
         4.44089210e-16],
       [ 2.77555756e-17,  3.46944695e-17, -2.49800181e-16,
         4.92661467e-16,  1.00000000e+00,  2.22044605e-16,
         5.55111512e-17],
       [ 1.66533454e-16, -1.38777878e-17, -5.55111512e-17,
         2.91433544e-16,  6.38378239e-16,  1.00000000e+00,
         2.22044605e-16],
       [-2.22044605e-16, -8.32667268e-17, -2.22044605e-16,
        -2.67147415e-16,  9.78384040e-16,  6.86950496e-16,
         1.0000000

In [220]:
mascara = resultado < 0.5
mascara

array([[False,  True,  True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True,  True,  True],
       [ True,  True,  True, False,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True,  True, False]])

In [223]:
resultado[mascara]

array([-1.07552856e-16, -2.08166817e-16,  4.96130914e-16,  1.45716772e-16,
        1.87350135e-16,  0.00000000e+00,  4.16333634e-17,  6.93889390e-17,
       -3.50414142e-16,  1.73472348e-16, -3.46944695e-17,  2.77555756e-16,
        6.93889390e-17,  9.36750677e-17,  6.00214323e-16,  8.25728375e-16,
        4.78783679e-16,  1.11022302e-16,  2.22044605e-16,  3.33066907e-16,
        2.22044605e-16,  4.44089210e-16,  1.66533454e-16,  4.44089210e-16,
        2.77555756e-17,  3.46944695e-17, -2.49800181e-16,  4.92661467e-16,
        2.22044605e-16,  5.55111512e-17,  1.66533454e-16, -1.38777878e-17,
       -5.55111512e-17,  2.91433544e-16,  6.38378239e-16,  2.22044605e-16,
       -2.22044605e-16, -8.32667268e-17, -2.22044605e-16, -2.67147415e-16,
        9.78384040e-16,  6.86950496e-16])

In [233]:
a = np.random.randint(0, 20, 60).reshape((10, 6))
a

array([[ 2,  0, 18, 10,  6,  8],
       [ 8, 11,  3, 18, 18,  1],
       [ 4,  5, 10, 18, 16,  0],
       [16, 17,  6, 12, 16, 19],
       [13, 18, 15, 13, 12, 14],
       [ 2, 10, 16, 18,  3, 14],
       [11, 15,  2,  3,  1, 14],
       [ 2, 19, 10,  9,  2,  0],
       [ 0,  5, 14, 14, 12, 10],
       [14, 16,  7, 18, 11,  8]])

In [242]:
mascara1 = a > 6
mascara1

array([[False, False,  True,  True, False,  True],
       [ True,  True, False,  True,  True, False],
       [False, False,  True,  True,  True, False],
       [ True,  True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [False,  True,  True,  True, False,  True],
       [ True,  True, False, False, False,  True],
       [False,  True,  True,  True, False, False],
       [False, False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [243]:
mascara2 = a < 15
mascara2

array([[ True,  True, False,  True,  True,  True],
       [ True,  True,  True, False, False,  True],
       [ True,  True,  True, False, False,  True],
       [False, False,  True,  True, False, False],
       [ True, False, False,  True,  True,  True],
       [ True,  True, False, False,  True,  True],
       [ True, False,  True,  True,  True,  True],
       [ True, False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True, False,  True, False,  True,  True]])

In [246]:
mascara = mascara1 * mascara2
mascara

array([[False, False, False,  True, False,  True],
       [ True,  True, False, False, False, False],
       [False, False,  True, False, False, False],
       [False, False, False,  True, False, False],
       [ True, False, False,  True,  True,  True],
       [False,  True, False, False, False,  True],
       [ True, False, False, False, False,  True],
       [False, False,  True,  True, False, False],
       [False, False,  True,  True,  True,  True],
       [ True, False,  True, False,  True,  True]])

In [247]:
a[mascara]

array([10,  8,  8, 11, 10, 12, 13, 13, 12, 14, 10, 14, 11, 14, 10,  9, 14,
       14, 12, 10, 14,  7, 11,  8])

In [250]:
True or False

True